from __future__ import annotations

import hashlib
import random
from datetime import date, timedelta
from decimal import Decimal

from app.core.config import settings
from app.ingestion.adapters.base import IngestionAdapter, NormalizedSignal


class MockSignalProvider(IngestionAdapter):
    source_name = "mock_provider"

    SIGNAL_TYPES = [
        "probate",
        "divorce",
        "tax_delinquency",
        "permit_activity",
        "stale_listing",
        "ownership_duration",
        "absentee_ownership",
        "insurance_distress",
    ]

    async def fetch_zip(self, zip_code: str) -> list[NormalizedSignal]:
        seed = int(hashlib.sha256(zip_code.encode("utf-8")).hexdigest()[:8], 16)
        rng = random.Random(seed)
        count = max(1, settings.simulated_signal_count)
        records: list[NormalizedSignal] = []
        for index in range(count):
            signal_type = self.SIGNAL_TYPES[(seed + index) % len(self.SIGNAL_TYPES)]
            subject_hash = hashlib.sha256(f"{zip_code}:{signal_type}:{index}".encode("utf-8")).hexdigest()
            event_age_days = rng.randint(1, 180)
            confidence = Decimal(str(round(rng.uniform(0.55, 0.96), 4)))
            street_number = 1000 + rng.randint(1, 8999)
            street_names = ["Coldwater Cyn", "Laurel Ave", "Maple Ridge Dr", "Ocean View Blvd"]
            address = f"{street_number} {street_names[index % len(street_names)]}"
            records.append(
                NormalizedSignal(
                    zip_code=zip_code,
                    signal_type=signal_type,
                    source=self.source_name,
                    subject_hash=subject_hash,
                    event_date=date.today() - timedelta(days=event_age_days),
                    confidence=confidence,
                    payload={
                        "demo": True,
                        "label": signal_type.replace("_", " ").title(),
                        "address": address,
                        "address_hash": hashlib.sha256(f"{zip_code}:addr:{index}".encode("utf-8")).hexdigest(),
                        "explainability": [
                            "Generated by deterministic mock provider",
                            f"Freshness age: {event_age_days} days",
                            f"Confidence: {confidence}",
                        ],
                    },
                )
            )
        return records
